version: 2

sphinx:
  configuration: docs/conf.py

# Build all formats

formats: all

conda:
  environment: docs/environment.yml

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - echo $PATH
      - wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.361/quarto-1.3.361-linux-amd64.tar.gz && mkdir ~/opt && tar -C ~/opt -xvzf quarto-1.3.361-linux-amd64.tar.gz
      - cd docs/ && make install
      - quarto render pl4y.qmd --output index.html
