version: 2

sphinx:
  configuration: docs/conf.py

# Build all formats

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
  jobs:
    pre_build:
      - echo $PATH
      - git clone https://github.com/quarto-dev/quarto-cli
      - cd quarto-cli && ./configure.sh
      - /usr/local/bin/quarto render pl4y.qmd --output index.html
